version: '3'

networks:
  mikroservisi:

services:
  eureka-serviceregistry:
    build: ./Eureca
    ports:
     - "8761:8761"
    tty: true
    networks:
      - mikroservisi

 # axon-server:
 #   image: axoniq/axonserver:4.3.2
 #   ports:
 #     - 8024:8024
 #     - 8124:8124

  book-service:
    build: ./Booking
    restart: always
    image: booking-image 
   # volumes:

    ports:
    - "8086:8086"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
  #    - axon-server    
    networks:
      - mikroservisi 


  auth-service:
    build: ./AthorizationAndAuthentication
    restart: always
    image: auth-image 
    volumes:
    - $USERPROFILE/Desktop/Mikroservisi/Logs:/tmp
    ports:
    - "8080:8080"
    environment:
     - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
 #     - axon-server    
    networks:
      - mikroservisi



  advert-service:
    build: ./Advertisement
    image: advert-image
    restart: always
    volumes:
    #- C:/Users/Sherlock/Desktop/Mikroservisi/Frontend/src/assets/images:/etc
    - C:/Users/Sherlock//Desktop/Mikroservisi/Loger:/tmp
    ports:
    - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
    #  - axon-server   
    networks:
      - mikroservisi

  message-service:
    build: ./Message
    restart: always
    image: message-image 
    volumes:
    - $USERPROFILE/Desktop/Mikroservisi/Logs:/tmp
    ports:
    - "8087:8087"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
  #    - axon-server    
    networks:
      - mikroservisi  


  zuul:
    build: ./Gateway
    volumes:
    - $USERPROFILE/Desktop/Mikroservisi/Gateway/src/main/resources:/etc
    ports:
    - "8443:8443"
    environment:
    - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
    #  - consumer-service
    #  - reglog-service
      - advert-service
      - book-service
      - auth-service
      - message-service
    networks:
      - mikroservisi


  