version: '3'

services:

  eureka-serviceregistry:
    build: ./Eureca
    ports:
     - "8761:8761"
    tty: true

 # axon-server:
 #   image: axoniq/axonserver:4.3.2
 #   ports:
 #     - 8024:8024
 #     - 8124:8124

#  book-service:
#    build: ./Booking
#    restart: always
#    image: booking-image 
#    volumes:
#    - $USERPROFILE/.m2:/root/.m2
#    - ./Booking
#    ports:
#    - "8086:8086"
#    environment:
#      - REGISTRY_HOST=eureka-serviceregistry
#    tty: true
#    depends_on:
#      - eureka-serviceregistry
  #    - axon-server    

  auth-service:
    build: ./AthorizationAndAuthentication
    restart: always
    image: auth-image 
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8080:8080"
    environment:
     - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
 #     - axon-server    



  advert-service:
    build: ./Advertisement
    image: advert-image
    restart: always
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
    #  - axon-server    

  zuul:
    build: ./Gateway
    ports:
    - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
    #  - consumer-service
    #  - reglog-service
      - advert-service
     # - book-service
      - auth-service

      