INSERT INTO BRAND(ID, NAME, CODE) VALUES (1, 'BMW', 'safku2');
INSERT INTO CAR_CLASS(ID, NAME, CODE) VALUES (1, 'Karavan', 'sa12ku2');
INSERT INTO FUEL_TYPE(ID, NAME, CODE) VALUES (1, 'Dizel', 'gj71');
INSERT INTO MODEL(ID, NAME, CODE) VALUES (1, 'FIRST', 'gsa2');
INSERT INTO TRANSMISSION_TYPE(ID, NAME, CODE) VALUES (1, 'Automatic', 'asd1');