INSERT INTO LOGIN_INFO (EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME)
VALUES ('admin@gmail.com', true, true, true, true, 'Susa$k0njina', 'admin');

INSERT INTO LOGIN_INFO (EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME)
VALUES ('user@gmail.com', true, true, true, true, 'Susa$k0njina', 'user');

INSERT INTO LOGIN_INFO (EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME)
VALUES ('kajza@gmail.com', true, true, true, true, 'Susa$k0njina', 'kajza');

INSERT INTO LOGIN_INFO (EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME)
VALUES ('agent@gmail.com', true, true, true, true, 'Susa$k0njina', 'agent');

INSERT INTO LOGIN_INFO (EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME)
VALUES ('sss', true, true, true, true, 'sss', 'sss');

INSERT INTO LOGIN_INFO (EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME)
VALUES ('ddd', true, true, true, true, 'ddd', 'ddd');


--USER
INSERT INTO USER_ENTITY (JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES
(0111997710268, 'Administrator', 0691408080, 'Administrator', 0, 1);

INSERT INTO USER_ENTITY (JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES
(0111997710260, 'Korisnik', 0691408082, 'Korisnik', 1, 2);

INSERT INTO USER_ENTITY (JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES
(0111997710263, 'Korisnik', 0691408082, 'Korisnik', 2, 3);

INSERT INTO USER_ENTITY (JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES
(0111997710265, 'Agent', 0691408082, 'Agent', 1, 4);

INSERT INTO USER_ENTITY (JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES
(0111997710273, 'Korisnik', 0691408082, 'Korisnik', 2, 5);

INSERT INTO USER_ENTITY (JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES
(0111997710265, 'Agent', 0691408082, 'Agent', 1, 6);

--ENDENTITY
INSERT INTO ENDENTITY (ACTIVATED, ADMIN_APPROVED, BLOCKED, NUMBER_OF_ADS, NUMBER_OF_REQUESTS_CANCELED, ENTITY_USER_ID) VALUES
(TRUE, TRUE, FALSE, 0, 0, 3);

INSERT INTO ENDENTITY (ACTIVATED, ADMIN_APPROVED, BLOCKED, NUMBER_OF_ADS, NUMBER_OF_REQUESTS_CANCELED, ENTITY_USER_ID) VALUES
 (FALSE, FALSE, FALSE, 0, 0, 2);

INSERT INTO ENDENTITY (ACTIVATED, ADMIN_APPROVED, BLOCKED, NUMBER_OF_ADS, NUMBER_OF_REQUESTS_CANCELED, ENTITY_USER_ID) VALUES
(TRUE, TRUE, FALSE, 0, 0, 5);


--AGENT
INSERT INTO AGENT (ADRESS, BUSINESS_REGISTRATION_NUMBER, FIRST_LOGIN, NUMBER_ADS, USER_ID) VALUES
('ADRESA', 54343, FALSE, 0, 2);

INSERT INTO AGENT (ADRESS, BUSINESS_REGISTRATION_NUMBER, FIRST_LOGIN, NUMBER_ADS, USER_ID) VALUES
('ADRESA', 54345, FALSE, 0, 6);
