INSERT INTO LOGIN_INFO (ID, EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME) 
VALUES (1, 'admin@gmail.com', true, true, true, true, 'Admin12345!', 'Admin');

INSERT INTO LOGIN_INFO (ID, EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED, IS_ENABLED,  PASSWORD, USERNAME) 
VALUES (2, 'user@gmail.com', true, true, true, true, 'User12345!', 'UserUser');

INSERT INTO USER_ENTITY (ID, JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES 
(1, 0111997710268, 'Administrator', 0691408080, 'Administrator', 0, 1);

INSERT INTO USER_ENTITY (ID, JMBG, NAME, PHONE_NUMBER, SURNAME, USER_TYPE, LOGIN_INFO) VALUES 
(2, 0111997710260, 'Korisnik', 0691408082, 'Korisnik', 2, 2);