//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 01:46:50 AM CEST 
//


package advertisement.com.javageneratedfiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userFromID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userToID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="advertisementIdInMonolith" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="together" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="groupID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="timeFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="timeTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="timeAccepted" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userFromID",
    "userToID",
    "advertisementIdInMonolith",
    "together",
    "groupID",
    "timeFrom",
    "timeTo",
    "timeAccepted"
})
@XmlRootElement(name = "getBookingRequest")
public class GetBookingRequest {

    protected long userFromID;
    protected long userToID;
    protected long advertisementIdInMonolith;
    protected boolean together;
    protected long groupID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeFrom;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeTo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeAccepted;

    /**
     * Gets the value of the userFromID property.
     * 
     */
    public long getUserFromID() {
        return userFromID;
    }

    /**
     * Sets the value of the userFromID property.
     * 
     */
    public void setUserFromID(long value) {
        this.userFromID = value;
    }

    /**
     * Gets the value of the userToID property.
     * 
     */
    public long getUserToID() {
        return userToID;
    }

    /**
     * Sets the value of the userToID property.
     * 
     */
    public void setUserToID(long value) {
        this.userToID = value;
    }

    /**
     * Gets the value of the advertisementIdInMonolith property.
     * 
     */
    public long getAdvertisementIdInMonolith() {
        return advertisementIdInMonolith;
    }

    /**
     * Sets the value of the advertisementIdInMonolith property.
     * 
     */
    public void setAdvertisementIdInMonolith(long value) {
        this.advertisementIdInMonolith = value;
    }

    /**
     * Gets the value of the together property.
     * 
     */
    public boolean isTogether() {
        return together;
    }

    /**
     * Sets the value of the together property.
     * 
     */
    public void setTogether(boolean value) {
        this.together = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     */
    public long getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     */
    public void setGroupID(long value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the timeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeFrom() {
        return timeFrom;
    }

    /**
     * Sets the value of the timeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeFrom(XMLGregorianCalendar value) {
        this.timeFrom = value;
    }

    /**
     * Gets the value of the timeTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeTo() {
        return timeTo;
    }

    /**
     * Sets the value of the timeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeTo(XMLGregorianCalendar value) {
        this.timeTo = value;
    }

    /**
     * Gets the value of the timeAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeAccepted() {
        return timeAccepted;
    }

    /**
     * Sets the value of the timeAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeAccepted(XMLGregorianCalendar value) {
        this.timeAccepted = value;
    }

}
